language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalagi123/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true kalagi123/docker-react-test npm run test
